#!/bin/sh

commit_msg=$(cat "$1")

if ! echo "$commit_msg" | grep -qE '^\[(Server|App|Camera|Repo)\]'; then
  echo ""
  echo "❌ Error: El mensaje del commit debe comenzar con [Server], [App], [Camera] o [Repo]"
  echo ""
  exit 1
fi
